{% set name = "djongo" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/djongo-{{ version }}.tar.gz
  sha256: 2250d484d4b4025661c139162bafd359eabaffd0deeba18debc59df78a325dc7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sqlparse ==0.2.4
    - pymongo >=3.2.0
    - django >=2.1
test:
  imports:
    - djongo
    - djongo.dynamic_formsets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://nesdis.github.io/djongo/
  summary: Driver for allowing Django to use MongoDB as the database backend.
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
    - rxm7706
